// GENERATED CODE
// Generated by the Java program at /build/annotationProcessors at compile time
// from annotations on Java methods. To update, change the annotations on the
// corresponding Java methods and rerun the build. Manually updating this file
// will cause your build to fail.

#include "FennecJNIWrappers.h"
#include "mozilla/jni/Accessors.h"

namespace mozilla {
namespace java {

const char ANRReporter::name[] =
        "org/mozilla/gecko/ANRReporter";

constexpr char ANRReporter::GetNativeStack_t::name[];
constexpr char ANRReporter::GetNativeStack_t::signature[];

constexpr char ANRReporter::ReleaseNativeStack_t::name[];
constexpr char ANRReporter::ReleaseNativeStack_t::signature[];

constexpr char ANRReporter::RequestNativeStack_t::name[];
constexpr char ANRReporter::RequestNativeStack_t::signature[];

const char DownloadsIntegration::name[] =
        "org/mozilla/gecko/DownloadsIntegration";

constexpr char DownloadsIntegration::GetTemporaryDownloadDirectory_t::name[];
constexpr char DownloadsIntegration::GetTemporaryDownloadDirectory_t::signature[];

auto DownloadsIntegration::GetTemporaryDownloadDirectory() -> mozilla::jni::String::LocalRef
{
    return mozilla::jni::Method<GetTemporaryDownloadDirectory_t>::Call(DownloadsIntegration::Context(), nullptr);
}

constexpr char DownloadsIntegration::ScanMedia_t::name[];
constexpr char DownloadsIntegration::ScanMedia_t::signature[];

auto DownloadsIntegration::ScanMedia(mozilla::jni::String::Param a0, mozilla::jni::String::Param a1) -> void
{
    return mozilla::jni::Method<ScanMedia_t>::Call(DownloadsIntegration::Context(), nullptr, a0, a1);
}

const char GeckoJavaSampler::name[] =
        "org/mozilla/gecko/GeckoJavaSampler";

constexpr char GeckoJavaSampler::GetFrameName_t::name[];
constexpr char GeckoJavaSampler::GetFrameName_t::signature[];

auto GeckoJavaSampler::GetFrameName(int32_t a0, int32_t a1, int32_t a2) -> mozilla::jni::String::LocalRef
{
    return mozilla::jni::Method<GetFrameName_t>::Call(GeckoJavaSampler::Context(), nullptr, a0, a1, a2);
}

constexpr char GeckoJavaSampler::GetProfilerTime_t::name[];
constexpr char GeckoJavaSampler::GetProfilerTime_t::signature[];

constexpr char GeckoJavaSampler::GetSampleTime_t::name[];
constexpr char GeckoJavaSampler::GetSampleTime_t::signature[];

auto GeckoJavaSampler::GetSampleTime(int32_t a0, int32_t a1) -> double
{
    return mozilla::jni::Method<GetSampleTime_t>::Call(GeckoJavaSampler::Context(), nullptr, a0, a1);
}

constexpr char GeckoJavaSampler::GetThreadName_t::name[];
constexpr char GeckoJavaSampler::GetThreadName_t::signature[];

auto GeckoJavaSampler::GetThreadName(int32_t a0) -> mozilla::jni::String::LocalRef
{
    return mozilla::jni::Method<GetThreadName_t>::Call(GeckoJavaSampler::Context(), nullptr, a0);
}

constexpr char GeckoJavaSampler::Pause_t::name[];
constexpr char GeckoJavaSampler::Pause_t::signature[];

auto GeckoJavaSampler::Pause() -> void
{
    return mozilla::jni::Method<Pause_t>::Call(GeckoJavaSampler::Context(), nullptr);
}

constexpr char GeckoJavaSampler::Start_t::name[];
constexpr char GeckoJavaSampler::Start_t::signature[];

auto GeckoJavaSampler::Start(int32_t a0, int32_t a1) -> void
{
    return mozilla::jni::Method<Start_t>::Call(GeckoJavaSampler::Context(), nullptr, a0, a1);
}

constexpr char GeckoJavaSampler::Stop_t::name[];
constexpr char GeckoJavaSampler::Stop_t::signature[];

auto GeckoJavaSampler::Stop() -> void
{
    return mozilla::jni::Method<Stop_t>::Call(GeckoJavaSampler::Context(), nullptr);
}

constexpr char GeckoJavaSampler::Unpause_t::name[];
constexpr char GeckoJavaSampler::Unpause_t::signature[];

auto GeckoJavaSampler::Unpause() -> void
{
    return mozilla::jni::Method<Unpause_t>::Call(GeckoJavaSampler::Context(), nullptr);
}

const char MemoryMonitor::name[] =
        "org/mozilla/gecko/MemoryMonitor";

constexpr char MemoryMonitor::DispatchMemoryPressure_t::name[];
constexpr char MemoryMonitor::DispatchMemoryPressure_t::signature[];

const char PresentationMediaPlayerManager::name[] =
        "org/mozilla/gecko/PresentationMediaPlayerManager";

constexpr char PresentationMediaPlayerManager::AddPresentationSurface_t::name[];
constexpr char PresentationMediaPlayerManager::AddPresentationSurface_t::signature[];

constexpr char PresentationMediaPlayerManager::InvalidateAndScheduleComposite_t::name[];
constexpr char PresentationMediaPlayerManager::InvalidateAndScheduleComposite_t::signature[];

constexpr char PresentationMediaPlayerManager::RemovePresentationSurface_t::name[];
constexpr char PresentationMediaPlayerManager::RemovePresentationSurface_t::signature[];

const char Telemetry::name[] =
        "org/mozilla/gecko/Telemetry";

constexpr char Telemetry::AddHistogram_t::name[];
constexpr char Telemetry::AddHistogram_t::signature[];

constexpr char Telemetry::AddKeyedHistogram_t::name[];
constexpr char Telemetry::AddKeyedHistogram_t::signature[];

constexpr char Telemetry::AddUIEvent_t::name[];
constexpr char Telemetry::AddUIEvent_t::signature[];

constexpr char Telemetry::StartUISession_t::name[];
constexpr char Telemetry::StartUISession_t::signature[];

constexpr char Telemetry::StopUISession_t::name[];
constexpr char Telemetry::StopUISession_t::signature[];

const char ThumbnailHelper::name[] =
        "org/mozilla/gecko/ThumbnailHelper";

constexpr char ThumbnailHelper::NotifyThumbnail_t::name[];
constexpr char ThumbnailHelper::NotifyThumbnail_t::signature[];

auto ThumbnailHelper::NotifyThumbnail(mozilla::jni::ByteBuffer::Param a0, mozilla::jni::Object::Param a1, bool a2, bool a3) -> void
{
    return mozilla::jni::Method<NotifyThumbnail_t>::Call(ThumbnailHelper::Context(), nullptr, a0, a1, a2, a3);
}

constexpr char ThumbnailHelper::RequestThumbnail_t::name[];
constexpr char ThumbnailHelper::RequestThumbnail_t::signature[];

const char ZoomedView::name[] =
        "org/mozilla/gecko/ZoomedView";

constexpr char ZoomedView::RequestZoomedViewData_t::name[];
constexpr char ZoomedView::RequestZoomedViewData_t::signature[];

const char AudioFocusAgent::name[] =
        "org/mozilla/gecko/media/AudioFocusAgent";

constexpr char AudioFocusAgent::NotifyStartedPlaying_t::name[];
constexpr char AudioFocusAgent::NotifyStartedPlaying_t::signature[];

auto AudioFocusAgent::NotifyStartedPlaying() -> void
{
    return mozilla::jni::Method<NotifyStartedPlaying_t>::Call(AudioFocusAgent::Context(), nullptr);
}

constexpr char AudioFocusAgent::NotifyStoppedPlaying_t::name[];
constexpr char AudioFocusAgent::NotifyStoppedPlaying_t::signature[];

auto AudioFocusAgent::NotifyStoppedPlaying() -> void
{
    return mozilla::jni::Method<NotifyStoppedPlaying_t>::Call(AudioFocusAgent::Context(), nullptr);
}

const char CodecProxy::name[] =
        "org/mozilla/gecko/media/CodecProxy";

constexpr char CodecProxy::Create_t::name[];
constexpr char CodecProxy::Create_t::signature[];

auto CodecProxy::Create(bool a0, mozilla::jni::Object::Param a1, mozilla::jni::Object::Param a2, mozilla::jni::Object::Param a3, mozilla::jni::String::Param a4) -> CodecProxy::LocalRef
{
    return mozilla::jni::Method<Create_t>::Call(CodecProxy::Context(), nullptr, a0, a1, a2, a3, a4);
}

constexpr char CodecProxy::Flush_t::name[];
constexpr char CodecProxy::Flush_t::signature[];

auto CodecProxy::Flush() const -> bool
{
    return mozilla::jni::Method<Flush_t>::Call(CodecProxy::mCtx, nullptr);
}

constexpr char CodecProxy::Input_t::name[];
constexpr char CodecProxy::Input_t::signature[];

auto CodecProxy::Input(mozilla::jni::ByteBuffer::Param a0, mozilla::jni::Object::Param a1, mozilla::jni::Object::Param a2) const -> bool
{
    return mozilla::jni::Method<Input_t>::Call(CodecProxy::mCtx, nullptr, a0, a1, a2);
}

constexpr char CodecProxy::IsAdaptivePlaybackSupported_t::name[];
constexpr char CodecProxy::IsAdaptivePlaybackSupported_t::signature[];

auto CodecProxy::IsAdaptivePlaybackSupported() const -> bool
{
    return mozilla::jni::Method<IsAdaptivePlaybackSupported_t>::Call(CodecProxy::mCtx, nullptr);
}

constexpr char CodecProxy::Release_t::name[];
constexpr char CodecProxy::Release_t::signature[];

auto CodecProxy::Release() const -> bool
{
    return mozilla::jni::Method<Release_t>::Call(CodecProxy::mCtx, nullptr);
}

constexpr char CodecProxy::ReleaseOutput_t::name[];
constexpr char CodecProxy::ReleaseOutput_t::signature[];

auto CodecProxy::ReleaseOutput(mozilla::jni::Object::Param a0, bool a1) const -> bool
{
    return mozilla::jni::Method<ReleaseOutput_t>::Call(CodecProxy::mCtx, nullptr, a0, a1);
}

constexpr char CodecProxy::SetRates_t::name[];
constexpr char CodecProxy::SetRates_t::signature[];

auto CodecProxy::SetRates(int32_t a0) const -> bool
{
    return mozilla::jni::Method<SetRates_t>::Call(CodecProxy::mCtx, nullptr, a0);
}

const char CodecProxy::NativeCallbacks::name[] =
        "org/mozilla/gecko/media/CodecProxy$NativeCallbacks";

constexpr char CodecProxy::NativeCallbacks::New_t::name[];
constexpr char CodecProxy::NativeCallbacks::New_t::signature[];

auto CodecProxy::NativeCallbacks::New() -> NativeCallbacks::LocalRef
{
    return mozilla::jni::Constructor<New_t>::Call(NativeCallbacks::Context(), nullptr);
}

constexpr char CodecProxy::NativeCallbacks::DisposeNative_t::name[];
constexpr char CodecProxy::NativeCallbacks::DisposeNative_t::signature[];

auto CodecProxy::NativeCallbacks::DisposeNative() const -> void
{
    return mozilla::jni::Method<DisposeNative_t>::Call(NativeCallbacks::mCtx, nullptr);
}

constexpr char CodecProxy::NativeCallbacks::OnError_t::name[];
constexpr char CodecProxy::NativeCallbacks::OnError_t::signature[];

constexpr char CodecProxy::NativeCallbacks::OnInputExhausted_t::name[];
constexpr char CodecProxy::NativeCallbacks::OnInputExhausted_t::signature[];

constexpr char CodecProxy::NativeCallbacks::OnOutput_t::name[];
constexpr char CodecProxy::NativeCallbacks::OnOutput_t::signature[];

constexpr char CodecProxy::NativeCallbacks::OnOutputFormatChanged_t::name[];
constexpr char CodecProxy::NativeCallbacks::OnOutputFormatChanged_t::signature[];

const char GeckoHlsDemuxerWrapper::name[] =
        "org/mozilla/gecko/media/GeckoHlsDemuxerWrapper";

constexpr char GeckoHlsDemuxerWrapper::Create_t::name[];
constexpr char GeckoHlsDemuxerWrapper::Create_t::signature[];

auto GeckoHlsDemuxerWrapper::Create(mozilla::jni::String::Param a0, mozilla::jni::Object::Param a1) -> GeckoHlsDemuxerWrapper::LocalRef
{
    return mozilla::jni::Method<Create_t>::Call(GeckoHlsDemuxerWrapper::Context(), nullptr, a0, a1);
}

constexpr char GeckoHlsDemuxerWrapper::Destroy_t::name[];
constexpr char GeckoHlsDemuxerWrapper::Destroy_t::signature[];

auto GeckoHlsDemuxerWrapper::Destroy() const -> void
{
    return mozilla::jni::Method<Destroy_t>::Call(GeckoHlsDemuxerWrapper::mCtx, nullptr);
}

constexpr char GeckoHlsDemuxerWrapper::GetAudioInfo_t::name[];
constexpr char GeckoHlsDemuxerWrapper::GetAudioInfo_t::signature[];

auto GeckoHlsDemuxerWrapper::GetAudioInfo(int32_t a0) const -> mozilla::jni::Object::LocalRef
{
    return mozilla::jni::Method<GetAudioInfo_t>::Call(GeckoHlsDemuxerWrapper::mCtx, nullptr, a0);
}

constexpr char GeckoHlsDemuxerWrapper::GetBuffered_t::name[];
constexpr char GeckoHlsDemuxerWrapper::GetBuffered_t::signature[];

auto GeckoHlsDemuxerWrapper::GetBuffered() const -> int64_t
{
    return mozilla::jni::Method<GetBuffered_t>::Call(GeckoHlsDemuxerWrapper::mCtx, nullptr);
}

constexpr char GeckoHlsDemuxerWrapper::GetNumberOfTracks_t::name[];
constexpr char GeckoHlsDemuxerWrapper::GetNumberOfTracks_t::signature[];

auto GeckoHlsDemuxerWrapper::GetNumberOfTracks(int32_t a0) const -> int32_t
{
    return mozilla::jni::Method<GetNumberOfTracks_t>::Call(GeckoHlsDemuxerWrapper::mCtx, nullptr, a0);
}

constexpr char GeckoHlsDemuxerWrapper::GetSamples_t::name[];
constexpr char GeckoHlsDemuxerWrapper::GetSamples_t::signature[];

auto GeckoHlsDemuxerWrapper::GetSamples(int32_t a0, int32_t a1) const -> mozilla::jni::ObjectArray::LocalRef
{
    return mozilla::jni::Method<GetSamples_t>::Call(GeckoHlsDemuxerWrapper::mCtx, nullptr, a0, a1);
}

constexpr char GeckoHlsDemuxerWrapper::GetVideoInfo_t::name[];
constexpr char GeckoHlsDemuxerWrapper::GetVideoInfo_t::signature[];

auto GeckoHlsDemuxerWrapper::GetVideoInfo(int32_t a0) const -> mozilla::jni::Object::LocalRef
{
    return mozilla::jni::Method<GetVideoInfo_t>::Call(GeckoHlsDemuxerWrapper::mCtx, nullptr, a0);
}

const char16_t GeckoHlsDemuxerWrapper::AAC[] = u"audio/mp4a-latm";

const char16_t GeckoHlsDemuxerWrapper::AVC[] = u"video/avc";

const char GeckoHlsDemuxerWrapper::HlsDemuxerCallbacks::name[] =
        "org/mozilla/gecko/media/GeckoHlsDemuxerWrapper$HlsDemuxerCallbacks";

constexpr char GeckoHlsDemuxerWrapper::HlsDemuxerCallbacks::New_t::name[];
constexpr char GeckoHlsDemuxerWrapper::HlsDemuxerCallbacks::New_t::signature[];

auto GeckoHlsDemuxerWrapper::HlsDemuxerCallbacks::New() -> HlsDemuxerCallbacks::LocalRef
{
    return mozilla::jni::Constructor<New_t>::Call(HlsDemuxerCallbacks::Context(), nullptr);
}

constexpr char GeckoHlsDemuxerWrapper::HlsDemuxerCallbacks::OnAudioFormatChanged_t::name[];
constexpr char GeckoHlsDemuxerWrapper::HlsDemuxerCallbacks::OnAudioFormatChanged_t::signature[];

constexpr char GeckoHlsDemuxerWrapper::HlsDemuxerCallbacks::OnDataArrived_t::name[];
constexpr char GeckoHlsDemuxerWrapper::HlsDemuxerCallbacks::OnDataArrived_t::signature[];

constexpr char GeckoHlsDemuxerWrapper::HlsDemuxerCallbacks::OnVideoFormatChanged_t::name[];
constexpr char GeckoHlsDemuxerWrapper::HlsDemuxerCallbacks::OnVideoFormatChanged_t::signature[];

const char HlsAudioInfo::name[] =
        "org/mozilla/gecko/media/HlsAudioInfo";

constexpr char HlsAudioInfo::New_t::name[];
constexpr char HlsAudioInfo::New_t::signature[];

auto HlsAudioInfo::New() -> HlsAudioInfo::LocalRef
{
    return mozilla::jni::Constructor<New_t>::Call(HlsAudioInfo::Context(), nullptr);
}

constexpr char HlsAudioInfo::BitDepth_t::name[];
constexpr char HlsAudioInfo::BitDepth_t::signature[];

auto HlsAudioInfo::BitDepth() const -> int32_t
{
    return mozilla::jni::Field<BitDepth_t>::Get(HlsAudioInfo::mCtx, nullptr);
}

auto HlsAudioInfo::BitDepth(int32_t a0) const -> void
{
    return mozilla::jni::Field<BitDepth_t>::Set(HlsAudioInfo::mCtx, nullptr, a0);
}

constexpr char HlsAudioInfo::Channels_t::name[];
constexpr char HlsAudioInfo::Channels_t::signature[];

auto HlsAudioInfo::Channels() const -> int32_t
{
    return mozilla::jni::Field<Channels_t>::Get(HlsAudioInfo::mCtx, nullptr);
}

auto HlsAudioInfo::Channels(int32_t a0) const -> void
{
    return mozilla::jni::Field<Channels_t>::Set(HlsAudioInfo::mCtx, nullptr, a0);
}

constexpr char HlsAudioInfo::CodecSpecificData_t::name[];
constexpr char HlsAudioInfo::CodecSpecificData_t::signature[];

auto HlsAudioInfo::CodecSpecificData() const -> mozilla::jni::ByteArray::LocalRef
{
    return mozilla::jni::Field<CodecSpecificData_t>::Get(HlsAudioInfo::mCtx, nullptr);
}

auto HlsAudioInfo::CodecSpecificData(mozilla::jni::ByteArray::Param a0) const -> void
{
    return mozilla::jni::Field<CodecSpecificData_t>::Set(HlsAudioInfo::mCtx, nullptr, a0);
}

constexpr char HlsAudioInfo::ExtraData_t::name[];
constexpr char HlsAudioInfo::ExtraData_t::signature[];

auto HlsAudioInfo::ExtraData() const -> mozilla::jni::ByteArray::LocalRef
{
    return mozilla::jni::Field<ExtraData_t>::Get(HlsAudioInfo::mCtx, nullptr);
}

auto HlsAudioInfo::ExtraData(mozilla::jni::ByteArray::Param a0) const -> void
{
    return mozilla::jni::Field<ExtraData_t>::Set(HlsAudioInfo::mCtx, nullptr, a0);
}

constexpr char HlsAudioInfo::MimeType_t::name[];
constexpr char HlsAudioInfo::MimeType_t::signature[];

auto HlsAudioInfo::MimeType() const -> mozilla::jni::String::LocalRef
{
    return mozilla::jni::Field<MimeType_t>::Get(HlsAudioInfo::mCtx, nullptr);
}

auto HlsAudioInfo::MimeType(mozilla::jni::String::Param a0) const -> void
{
    return mozilla::jni::Field<MimeType_t>::Set(HlsAudioInfo::mCtx, nullptr, a0);
}

constexpr char HlsAudioInfo::Profile_t::name[];
constexpr char HlsAudioInfo::Profile_t::signature[];

auto HlsAudioInfo::Profile() const -> int32_t
{
    return mozilla::jni::Field<Profile_t>::Get(HlsAudioInfo::mCtx, nullptr);
}

auto HlsAudioInfo::Profile(int32_t a0) const -> void
{
    return mozilla::jni::Field<Profile_t>::Set(HlsAudioInfo::mCtx, nullptr, a0);
}

constexpr char HlsAudioInfo::Rate_t::name[];
constexpr char HlsAudioInfo::Rate_t::signature[];

auto HlsAudioInfo::Rate() const -> int32_t
{
    return mozilla::jni::Field<Rate_t>::Get(HlsAudioInfo::mCtx, nullptr);
}

auto HlsAudioInfo::Rate(int32_t a0) const -> void
{
    return mozilla::jni::Field<Rate_t>::Set(HlsAudioInfo::mCtx, nullptr, a0);
}

const char HlsVideoInfo::name[] =
        "org/mozilla/gecko/media/HlsVideoInfo";

constexpr char HlsVideoInfo::New_t::name[];
constexpr char HlsVideoInfo::New_t::signature[];

auto HlsVideoInfo::New() -> HlsVideoInfo::LocalRef
{
    return mozilla::jni::Constructor<New_t>::Call(HlsVideoInfo::Context(), nullptr);
}

constexpr char HlsVideoInfo::CodecSpecificData_t::name[];
constexpr char HlsVideoInfo::CodecSpecificData_t::signature[];

auto HlsVideoInfo::CodecSpecificData() const -> mozilla::jni::ByteArray::LocalRef
{
    return mozilla::jni::Field<CodecSpecificData_t>::Get(HlsVideoInfo::mCtx, nullptr);
}

auto HlsVideoInfo::CodecSpecificData(mozilla::jni::ByteArray::Param a0) const -> void
{
    return mozilla::jni::Field<CodecSpecificData_t>::Set(HlsVideoInfo::mCtx, nullptr, a0);
}

constexpr char HlsVideoInfo::DisplayX_t::name[];
constexpr char HlsVideoInfo::DisplayX_t::signature[];

auto HlsVideoInfo::DisplayX() const -> int32_t
{
    return mozilla::jni::Field<DisplayX_t>::Get(HlsVideoInfo::mCtx, nullptr);
}

auto HlsVideoInfo::DisplayX(int32_t a0) const -> void
{
    return mozilla::jni::Field<DisplayX_t>::Set(HlsVideoInfo::mCtx, nullptr, a0);
}

constexpr char HlsVideoInfo::DisplayY_t::name[];
constexpr char HlsVideoInfo::DisplayY_t::signature[];

auto HlsVideoInfo::DisplayY() const -> int32_t
{
    return mozilla::jni::Field<DisplayY_t>::Get(HlsVideoInfo::mCtx, nullptr);
}

auto HlsVideoInfo::DisplayY(int32_t a0) const -> void
{
    return mozilla::jni::Field<DisplayY_t>::Set(HlsVideoInfo::mCtx, nullptr, a0);
}

constexpr char HlsVideoInfo::ExtraData_t::name[];
constexpr char HlsVideoInfo::ExtraData_t::signature[];

auto HlsVideoInfo::ExtraData() const -> mozilla::jni::ByteArray::LocalRef
{
    return mozilla::jni::Field<ExtraData_t>::Get(HlsVideoInfo::mCtx, nullptr);
}

auto HlsVideoInfo::ExtraData(mozilla::jni::ByteArray::Param a0) const -> void
{
    return mozilla::jni::Field<ExtraData_t>::Set(HlsVideoInfo::mCtx, nullptr, a0);
}

constexpr char HlsVideoInfo::MimeType_t::name[];
constexpr char HlsVideoInfo::MimeType_t::signature[];

auto HlsVideoInfo::MimeType() const -> mozilla::jni::String::LocalRef
{
    return mozilla::jni::Field<MimeType_t>::Get(HlsVideoInfo::mCtx, nullptr);
}

auto HlsVideoInfo::MimeType(mozilla::jni::String::Param a0) const -> void
{
    return mozilla::jni::Field<MimeType_t>::Set(HlsVideoInfo::mCtx, nullptr, a0);
}

constexpr char HlsVideoInfo::PictureX_t::name[];
constexpr char HlsVideoInfo::PictureX_t::signature[];

auto HlsVideoInfo::PictureX() const -> int32_t
{
    return mozilla::jni::Field<PictureX_t>::Get(HlsVideoInfo::mCtx, nullptr);
}

auto HlsVideoInfo::PictureX(int32_t a0) const -> void
{
    return mozilla::jni::Field<PictureX_t>::Set(HlsVideoInfo::mCtx, nullptr, a0);
}

constexpr char HlsVideoInfo::PictureY_t::name[];
constexpr char HlsVideoInfo::PictureY_t::signature[];

auto HlsVideoInfo::PictureY() const -> int32_t
{
    return mozilla::jni::Field<PictureY_t>::Get(HlsVideoInfo::mCtx, nullptr);
}

auto HlsVideoInfo::PictureY(int32_t a0) const -> void
{
    return mozilla::jni::Field<PictureY_t>::Set(HlsVideoInfo::mCtx, nullptr, a0);
}

constexpr char HlsVideoInfo::Rotation_t::name[];
constexpr char HlsVideoInfo::Rotation_t::signature[];

auto HlsVideoInfo::Rotation() const -> int32_t
{
    return mozilla::jni::Field<Rotation_t>::Get(HlsVideoInfo::mCtx, nullptr);
}

auto HlsVideoInfo::Rotation(int32_t a0) const -> void
{
    return mozilla::jni::Field<Rotation_t>::Set(HlsVideoInfo::mCtx, nullptr, a0);
}

constexpr char HlsVideoInfo::StereoMode_t::name[];
constexpr char HlsVideoInfo::StereoMode_t::signature[];

auto HlsVideoInfo::StereoMode() const -> int32_t
{
    return mozilla::jni::Field<StereoMode_t>::Get(HlsVideoInfo::mCtx, nullptr);
}

auto HlsVideoInfo::StereoMode(int32_t a0) const -> void
{
    return mozilla::jni::Field<StereoMode_t>::Set(HlsVideoInfo::mCtx, nullptr, a0);
}

const char MediaDrmProxy::name[] =
        "org/mozilla/gecko/media/MediaDrmProxy";

constexpr char MediaDrmProxy::CanDecode_t::name[];
constexpr char MediaDrmProxy::CanDecode_t::signature[];

auto MediaDrmProxy::CanDecode(mozilla::jni::String::Param a0) -> bool
{
    return mozilla::jni::Method<CanDecode_t>::Call(MediaDrmProxy::Context(), nullptr, a0);
}

constexpr char MediaDrmProxy::IsCryptoSchemeSupported_t::name[];
constexpr char MediaDrmProxy::IsCryptoSchemeSupported_t::signature[];

auto MediaDrmProxy::IsCryptoSchemeSupported(mozilla::jni::String::Param a0, mozilla::jni::String::Param a1) -> bool
{
    return mozilla::jni::Method<IsCryptoSchemeSupported_t>::Call(MediaDrmProxy::Context(), nullptr, a0, a1);
}

constexpr char MediaDrmProxy::CloseSession_t::name[];
constexpr char MediaDrmProxy::CloseSession_t::signature[];

auto MediaDrmProxy::CloseSession(int32_t a0, mozilla::jni::String::Param a1) const -> void
{
    return mozilla::jni::Method<CloseSession_t>::Call(MediaDrmProxy::mCtx, nullptr, a0, a1);
}

constexpr char MediaDrmProxy::Create_t::name[];
constexpr char MediaDrmProxy::Create_t::signature[];

auto MediaDrmProxy::Create(mozilla::jni::String::Param a0, mozilla::jni::Object::Param a1) -> MediaDrmProxy::LocalRef
{
    return mozilla::jni::Method<Create_t>::Call(MediaDrmProxy::Context(), nullptr, a0, a1);
}

constexpr char MediaDrmProxy::CreateSession_t::name[];
constexpr char MediaDrmProxy::CreateSession_t::signature[];

auto MediaDrmProxy::CreateSession(int32_t a0, int32_t a1, mozilla::jni::String::Param a2, mozilla::jni::ByteArray::Param a3) const -> void
{
    return mozilla::jni::Method<CreateSession_t>::Call(MediaDrmProxy::mCtx, nullptr, a0, a1, a2, a3);
}

constexpr char MediaDrmProxy::Destroy_t::name[];
constexpr char MediaDrmProxy::Destroy_t::signature[];

auto MediaDrmProxy::Destroy() const -> void
{
    return mozilla::jni::Method<Destroy_t>::Call(MediaDrmProxy::mCtx, nullptr);
}

constexpr char MediaDrmProxy::GetMediaCrypto_t::name[];
constexpr char MediaDrmProxy::GetMediaCrypto_t::signature[];

auto MediaDrmProxy::GetMediaCrypto(mozilla::jni::String::Param a0) -> mozilla::jni::Object::LocalRef
{
    return mozilla::jni::Method<GetMediaCrypto_t>::Call(MediaDrmProxy::Context(), nullptr, a0);
}

constexpr char MediaDrmProxy::GetStubId_t::name[];
constexpr char MediaDrmProxy::GetStubId_t::signature[];

auto MediaDrmProxy::GetStubId() const -> mozilla::jni::String::LocalRef
{
    return mozilla::jni::Method<GetStubId_t>::Call(MediaDrmProxy::mCtx, nullptr);
}

constexpr char MediaDrmProxy::IsSchemeSupported_t::name[];
constexpr char MediaDrmProxy::IsSchemeSupported_t::signature[];

auto MediaDrmProxy::IsSchemeSupported(mozilla::jni::String::Param a0) -> bool
{
    return mozilla::jni::Method<IsSchemeSupported_t>::Call(MediaDrmProxy::Context(), nullptr, a0);
}

constexpr char MediaDrmProxy::UpdateSession_t::name[];
constexpr char MediaDrmProxy::UpdateSession_t::signature[];

auto MediaDrmProxy::UpdateSession(int32_t a0, mozilla::jni::String::Param a1, mozilla::jni::ByteArray::Param a2) const -> void
{
    return mozilla::jni::Method<UpdateSession_t>::Call(MediaDrmProxy::mCtx, nullptr, a0, a1, a2);
}

const char16_t MediaDrmProxy::AAC[] = u"audio/mp4a-latm";

const char16_t MediaDrmProxy::AVC[] = u"video/avc";

const char16_t MediaDrmProxy::OPUS[] = u"audio/opus";

const char16_t MediaDrmProxy::VORBIS[] = u"audio/vorbis";

const char16_t MediaDrmProxy::VP8[] = u"video/x-vnd.on2.vp8";

const char16_t MediaDrmProxy::VP9[] = u"video/x-vnd.on2.vp9";

const char MediaDrmProxy::NativeMediaDrmProxyCallbacks::name[] =
        "org/mozilla/gecko/media/MediaDrmProxy$NativeMediaDrmProxyCallbacks";

constexpr char MediaDrmProxy::NativeMediaDrmProxyCallbacks::New_t::name[];
constexpr char MediaDrmProxy::NativeMediaDrmProxyCallbacks::New_t::signature[];

auto MediaDrmProxy::NativeMediaDrmProxyCallbacks::New() -> NativeMediaDrmProxyCallbacks::LocalRef
{
    return mozilla::jni::Constructor<New_t>::Call(NativeMediaDrmProxyCallbacks::Context(), nullptr);
}

constexpr char MediaDrmProxy::NativeMediaDrmProxyCallbacks::OnRejectPromise_t::name[];
constexpr char MediaDrmProxy::NativeMediaDrmProxyCallbacks::OnRejectPromise_t::signature[];

constexpr char MediaDrmProxy::NativeMediaDrmProxyCallbacks::OnSessionBatchedKeyChanged_t::name[];
constexpr char MediaDrmProxy::NativeMediaDrmProxyCallbacks::OnSessionBatchedKeyChanged_t::signature[];

constexpr char MediaDrmProxy::NativeMediaDrmProxyCallbacks::OnSessionClosed_t::name[];
constexpr char MediaDrmProxy::NativeMediaDrmProxyCallbacks::OnSessionClosed_t::signature[];

constexpr char MediaDrmProxy::NativeMediaDrmProxyCallbacks::OnSessionCreated_t::name[];
constexpr char MediaDrmProxy::NativeMediaDrmProxyCallbacks::OnSessionCreated_t::signature[];

constexpr char MediaDrmProxy::NativeMediaDrmProxyCallbacks::OnSessionError_t::name[];
constexpr char MediaDrmProxy::NativeMediaDrmProxyCallbacks::OnSessionError_t::signature[];

constexpr char MediaDrmProxy::NativeMediaDrmProxyCallbacks::OnSessionMessage_t::name[];
constexpr char MediaDrmProxy::NativeMediaDrmProxyCallbacks::OnSessionMessage_t::signature[];

constexpr char MediaDrmProxy::NativeMediaDrmProxyCallbacks::OnSessionUpdated_t::name[];
constexpr char MediaDrmProxy::NativeMediaDrmProxyCallbacks::OnSessionUpdated_t::signature[];

const char Sample::name[] =
        "org/mozilla/gecko/media/Sample";

constexpr char Sample::WriteToByteBuffer_t::name[];
constexpr char Sample::WriteToByteBuffer_t::signature[];

auto Sample::WriteToByteBuffer(mozilla::jni::ByteBuffer::Param a0) const -> void
{
    return mozilla::jni::Method<WriteToByteBuffer_t>::Call(Sample::mCtx, nullptr, a0);
}

constexpr char Sample::CryptoInfo_t::name[];
constexpr char Sample::CryptoInfo_t::signature[];

auto Sample::CryptoInfo() const -> mozilla::jni::Object::LocalRef
{
    return mozilla::jni::Field<CryptoInfo_t>::Get(Sample::mCtx, nullptr);
}

auto Sample::CryptoInfo(mozilla::jni::Object::Param a0) const -> void
{
    return mozilla::jni::Field<CryptoInfo_t>::Set(Sample::mCtx, nullptr, a0);
}

constexpr char Sample::Info_t::name[];
constexpr char Sample::Info_t::signature[];

auto Sample::Info() const -> mozilla::jni::Object::LocalRef
{
    return mozilla::jni::Field<Info_t>::Get(Sample::mCtx, nullptr);
}

auto Sample::Info(mozilla::jni::Object::Param a0) const -> void
{
    return mozilla::jni::Field<Info_t>::Set(Sample::mCtx, nullptr, a0);
}

const char SessionKeyInfo::name[] =
        "org/mozilla/gecko/media/SessionKeyInfo";

constexpr char SessionKeyInfo::New_t::name[];
constexpr char SessionKeyInfo::New_t::signature[];

auto SessionKeyInfo::New(mozilla::jni::ByteArray::Param a0, int32_t a1) -> SessionKeyInfo::LocalRef
{
    return mozilla::jni::Constructor<New_t>::Call(SessionKeyInfo::Context(), nullptr, a0, a1);
}

constexpr char SessionKeyInfo::KeyId_t::name[];
constexpr char SessionKeyInfo::KeyId_t::signature[];

auto SessionKeyInfo::KeyId() const -> mozilla::jni::ByteArray::LocalRef
{
    return mozilla::jni::Field<KeyId_t>::Get(SessionKeyInfo::mCtx, nullptr);
}

auto SessionKeyInfo::KeyId(mozilla::jni::ByteArray::Param a0) const -> void
{
    return mozilla::jni::Field<KeyId_t>::Set(SessionKeyInfo::mCtx, nullptr, a0);
}

constexpr char SessionKeyInfo::Status_t::name[];
constexpr char SessionKeyInfo::Status_t::signature[];

auto SessionKeyInfo::Status() const -> int32_t
{
    return mozilla::jni::Field<Status_t>::Get(SessionKeyInfo::mCtx, nullptr);
}

auto SessionKeyInfo::Status(int32_t a0) const -> void
{
    return mozilla::jni::Field<Status_t>::Set(SessionKeyInfo::mCtx, nullptr, a0);
}

const char Restrictions::name[] =
        "org/mozilla/gecko/restrictions/Restrictions";

constexpr char Restrictions::IsAllowed_t::name[];
constexpr char Restrictions::IsAllowed_t::signature[];

auto Restrictions::IsAllowed(int32_t a0, mozilla::jni::String::Param a1) -> bool
{
    return mozilla::jni::Method<IsAllowed_t>::Call(Restrictions::Context(), nullptr, a0, a1);
}

constexpr char Restrictions::IsUserRestricted_t::name[];
constexpr char Restrictions::IsUserRestricted_t::signature[];

auto Restrictions::IsUserRestricted() -> bool
{
    return mozilla::jni::Method<IsUserRestricted_t>::Call(Restrictions::Context(), nullptr);
}

} /* java */
} /* mozilla */
